services:
  chat_app:
    depends_on:
      - mysql
      - neo4j
    build:
      context: ../
    networks:
      - checking
    ports:
      - 80:8081
    environment:
      - DB_HOST=host.docker.internal
    deploy:
      restart_policy:
        condition: on-failure
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYPASSWORD:-12345678}
    volumes:
      - mysql:/var/lib/mysql
      - ../internal/dataaccess/database/migrations/mysql/0001.initialize.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - checking
    ports:
      - 3306:3306
    expose:
      - 3306
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    restart: always
    ports:
      - 7687:7687
      - 7474:7474
    volumes:
      - neo4j:/data
    environment:
      - NEO4J_AUTH=${NEO_AUTH:-neo4j/12345678}
    networks:
      - checking
    expose:
      - 7474

volumes:
  mysql:
    driver: local
  neo4j:


networks:
  checking:
    driver: bridge