// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package database

import (
	"github.com/ChatService/internal/configs"
	"github.com/google/wire"
)

// Injectors from wire.go:

func getAccountAccessor(path configs.ConfigFilePath) (AccountDataAccessor, func(), error) {
	config, err := configs.NewConfig(path)
	if err != nil {
		return nil, nil, err
	}
	database := config.Database
	db, cleanup, err := InitializeAndMigrateUpDB(database)
	if err != nil {
		return nil, nil, err
	}
	gormDB, err := InitializeGorm(db, database)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	databaseAccountDataAccessor := InitializeAccountDataAccessor(gormDB)
	return databaseAccountDataAccessor, func() {
		cleanup()
	}, nil
}

// wire.go:

var wireSetInternal = wire.NewSet(
	WireSet, configs.Wireset,
)
