// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/ChatService/internal/configs"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeStandaloneServer(path configs.ConfigFilePath) (StandaloneServer, error) {
	config, err := configs.NewConfig(path)
	if err != nil {
		return nil, err
	}
	appStandaloneServer := NewStandaloneServer(config)
	return appStandaloneServer, nil
}

// wire.go:

var WireSet = wire.NewSet(configs.Wireset, NewStandaloneServer)
