database:
  host: 0.0.0.0
  port: 3306
  username: root
  password: 12345678
  database: chat
  type: mysql
http:
  address: "0.0.0.0:8081"
auth:
  hash:
    cost: 10
  token:
    expires_in: 24
    signed_key: hello_world
graphdb:
  type: neo4j
  database: neo4j
  password: 12345678
  host: 0.0.0.0
  username: neo4j
