database:
  host: 127.0.0.1
  port: 3306
  username: root
  password: 12345678
  database: chat
  type: mysql
http:
  address: "0.0.0.0:8081"
auth:
  hash:
    cost: 10
  token:
    expires_in: 24
    signed_key: hello_world
