// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func Initialize() (C, error) {
	string2 := GetContentA()
	a := ContentA(string2)
	contB := GetContentB()
	b := ContentB(a, contB)
	c := b.contentC
	return c, nil
}
